#!/usr/bin/env python3
"""
update.py — NoEyes self-updater

Pulls the latest version from GitHub and replaces the tool files in-place.
Your keys, config, identity, and received files are NEVER touched.

Integrity verification:
  Every update downloads a manifest.json containing the SHA-256 hash of each
  file at that commit.  Every downloaded file is verified against the manifest
  before anything is written to disk.  If any hash mismatches the update is
  aborted with no changes made.

  This protects against:
    · In-transit corruption or partial downloads
    · A network attacker tampering with files in transit (even over HTTPS)
    · Accidental corruption on GitHub's CDN

  The manifest is Ed25519-signed with an offline key that never touches the
  repo.  update.py verifies the signature against a hardcoded public key before
  trusting any hash in the manifest.  A compromised GitHub account cannot push
  a valid signed manifest without the repo owner's private key.

Usage:
    python update.py           — update to latest
    python update.py --check   — check if an update is available, don't install
    python update.py --force   — re-download and reinstall even if up to date
"""

import argparse, hashlib, json, os, shutil, sys, tempfile, urllib.request

# ---------------------------------------------------------------------------
# Release signing public key
# ---------------------------------------------------------------------------
# This is the Ed25519 public key for verifying manifest.json signatures.
# It is hardcoded here so that even if an attacker gains push access to the
# GitHub repo, they cannot forge a valid manifest without the private key,
# which the repo owner keeps offline.
# To rotate the key: update this constant and re-sign all manifests with the
# new private key using gen_manifest.py.
RELEASE_PUBKEY_HEX = "22942493dda8680355434ad623b707db2fd40a4656d40b1d13288bef433f8654"

from pathlib import Path

REPO_OWNER = "Ymsniper"
REPO_NAME  = "NoEyes"
GITHUB_API = f"https://api.github.com/repos/{REPO_OWNER}/{REPO_NAME}"
RAW_BASE   = f"https://raw.githubusercontent.com/{REPO_OWNER}/{REPO_NAME}"

# manifest.json in the repo root — contains {filename: sha256hex} for every
# file in TOOL_FILES.  Generated by the repo maintainer on each release.
MANIFEST_FILE = "manifest.json"

TOOL_FILES = [
    # entry points
    "noeyes.py", "update.py", "gen_manifest.py",
    # core package
    "core/__init__.py",
    "core/encryption.py", "core/identity.py", "core/utils.py",
    "core/config.py", "core/firewall.py",
    # network package
    "network/__init__.py",
    "network/server.py", "network/client.py",
    # UI / helpers
    "ui/__init__.py",
    "ui/launch.py", "ui/setup.py",
    # install / bootstrap
    "install/__init__.py",
    "install/install.sh", "install/install.ps1",
    "install/install.bat", "install/install.py",
    # tests
    "tests/__init__.py",
    "tests/selftest.py",
    "tests/test_launch_windows.py", "tests/test_utils_windows.py",
    # docs
    "docs/README.md", "docs/CHANGELOG.md", "docs/CONNECTION_GUIDE.md",
    # misc
    "requirements.txt", "manifest.json", "noeyes_config.json.example",
    "setup_firewall.sh", "demo.svg",
    # sfx
    "sfx/diskette.mp3", "sfx/crt.mp3", "sfx/logo.mp3",
]

PROTECTED = {
    "files", "chat.key", "noeyes_config.json",
    ".noeyes_version", ".noeyes_backup",
}

HERE = Path(__file__).parent.resolve()


def _get(url, timeout=15):
    req = urllib.request.Request(url, headers={"User-Agent": f"NoEyes-updater/{REPO_OWNER}"})
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return r.read()

def _get_json(url):
    return json.loads(_get(url))

def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()

def _c(code, msg): return f"\033[{code}m{msg}\033[0m"
def ok(m):   print(_c("92", f"  ✔  {m}"))
def warn(m): print(_c("93", f"  !  {m}"))
def err(m):  print(_c("91", f"  ✘  {m}"))
def info(m): print(_c("90", f"  ·  {m}"))


def latest_commit():
    for branch in ("main", "master"):
        try:
            d = _get_json(f"{GITHUB_API}/commits/{branch}")
            return {"sha": d["sha"], "short": d["sha"][:7],
                    "message": d["commit"]["message"].splitlines()[0],
                    "author":  d["commit"]["author"]["name"],
                    "date":    d["commit"]["author"]["date"][:10],
                    "branch":  branch}
        except Exception:
            continue
    err("Could not reach GitHub. Check your internet connection.")
    sys.exit(1)

def local_commit():
    p = HERE / ".noeyes_version"
    return p.read_text().strip() if p.exists() else ""

def save_commit(sha):
    (HERE / ".noeyes_version").write_text(sha)

def download(filename, branch, dest):
    try:
        data = _get(f"{RAW_BASE}/{branch}/{filename}")
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(data)
        return data
    except Exception as e:
        err(f"Failed to download {filename}: {e}")
        return None


def cmd_check():
    info("Checking for updates…")
    lo = local_commit(); re = latest_commit()
    if not lo:
        warn("No version info found — run  python update.py  to install.")
        return
    if lo == re["sha"]:
        ok(f"Already up to date  ({re['short']} · {re['date']})")
    else:
        warn("Update available!")
        info(f"Installed : {lo[:7]}")
        info(f"Latest    : {re['short']} — {re['message']}  ({re['date']})")
        info("Run  python update.py  to install.")


def cmd_update(force=False):
    info("Checking for updates…")
    lo = local_commit(); re = latest_commit()

    if lo == re["sha"] and not force:
        ok(f"Already up to date  ({re['short']} · {re['date']})")
        return

    print()
    print(_c("96", f"  {'Updating' if lo else 'Installing'}  "
             f"{lo[:7] + ' → ' if lo else ''}{re['short']}"))
    info(f"{re['message']}  by {re['author']}  on {re['date']}")
    print()

    with tempfile.TemporaryDirectory() as tmpdir:
        tmp = Path(tmpdir)

        # ── Step 1: Download and verify manifest signature ───────────────────
        info("Downloading integrity manifest…")
        try:
            manifest_data = _get(f"{RAW_BASE}/{re['branch']}/{MANIFEST_FILE}")
            manifest_obj  = json.loads(manifest_data)
        except Exception as e:
            err(f"Could not download manifest.json: {e}")
            err("Aborting — your installation is unchanged.")
            sys.exit(1)

        # Verify Ed25519 signature before trusting any hash in the manifest.
        # The canonical bytes are the sorted-keys compact JSON of the "files"
        # dict — exactly what gen_manifest.py signs.
        try:
            from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey
            from cryptography.hazmat.primitives.serialization import Encoding, PublicFormat
            from cryptography.exceptions import InvalidSignature

            vk = Ed25519PublicKey.from_public_bytes(bytes.fromhex(RELEASE_PUBKEY_HEX))
            files_dict = manifest_obj.get("files", {})
            canonical  = json.dumps(files_dict, sort_keys=True, separators=(",", ":")).encode()
            sig_hex    = manifest_obj.get("sig", "")
            if not sig_hex:
                err("manifest.json has no signature field.")
                err("Aborting — your installation is unchanged.")
                sys.exit(1)
            vk.verify(bytes.fromhex(sig_hex), canonical)
            ok("Manifest signature verified.")
            manifest = files_dict
        except InvalidSignature:
            err("MANIFEST SIGNATURE INVALID!")
            err("The manifest may have been tampered with.")
            err("Do NOT update until you can verify the repo is clean.")
            err("Aborting — your installation is unchanged.")
            sys.exit(1)
        except Exception as e:
            err(f"Signature verification failed: {e}")
            err("Aborting — your installation is unchanged.")
            sys.exit(1)

        # ── Step 2: Download all files ────────────────────────────────────────
        info("Downloading files…")
        downloaded: dict[str, bytes] = {}
        failed = []
        for f in TOOL_FILES:
            data = download(f, re["branch"], tmp / f)
            if data is not None:
                downloaded[f] = data
                info(f"  ✓ {f}")
            else:
                failed.append(f)

        if failed:
            print()
            err(f"Download failed for: {', '.join(failed)}")
            err("Aborting — your installation is unchanged.")
            sys.exit(1)

        # ── Step 3: Verify hashes against manifest ────────────────────────────
        if manifest:
            info("Verifying file integrity…")
            bad = []
            for f, data in downloaded.items():
                expected = manifest.get(f)
                if expected is None:
                    # File not in manifest — warn but allow (new file added)
                    warn(f"  ? {f}  not in manifest — cannot verify")
                    continue
                actual = _sha256(data)
                if actual != expected:
                    err(f"  ✘ {f}  HASH MISMATCH")
                    err(f"      expected : {expected[:16]}…")
                    err(f"      got      : {actual[:16]}…")
                    bad.append(f)
                else:
                    info(f"  ✔ {f}  verified")

            if bad:
                print()
                err(f"Integrity check FAILED for: {', '.join(bad)}")
                err("This could indicate tampering or a corrupted download.")
                err("Aborting — your installation is unchanged.")
                err("Try again, or download manually from GitHub and verify.")
                sys.exit(1)

            ok("All files verified.")
        print()

        # ── Step 4: Install (only runs if all hashes passed) ──────────────────
        info("Installing…")
        backup = HERE / ".noeyes_backup"
        backup.mkdir(exist_ok=True)
        replaced = []

        try:
            for f in TOOL_FILES:
                src = tmp / f; dest = HERE / f
                parts = dest.relative_to(HERE).parts
                if parts[0] in PROTECTED or dest.name in PROTECTED:
                    continue
                if not src.exists():
                    continue
                if dest.exists():
                    (backup / f).parent.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(dest, backup / f)
                dest.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(src, dest)
                replaced.append(f)
        except Exception as e:
            err(f"Install error: {e}")
            warn("Rolling back…")
            for f in replaced:
                b = backup / f
                if b.exists(): shutil.copy2(b, HERE / f)
            warn("Rolled back — your installation is unchanged.")
            sys.exit(1)

    save_commit(re["sha"])
    print()
    ok(f"Updated to {re['short']} successfully!")
    info(f"{len(replaced)} file(s) replaced.")
    info("Backup saved to .noeyes_backup/")
    info("Keys, identity, config, and received files were not touched.")
    print()
    info("Run  python setup.py --check  to verify all dependencies are up to date.")


def main():
    ap = argparse.ArgumentParser(description="NoEyes self-updater")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()
    cmd_check() if args.check else cmd_update(force=args.force)

if __name__ == "__main__":
    main()
